### ISSUE TITLE
Not able to process Sendgrid events

### ISSUE THREAD

**Issue by dwoods-encircle** [aghstrategies/com.aghstrategies.airmail#55]
We installed latest version on Civi 5.69.5 with PHP 8.1.

Setup the Sendgrid webhook and confirmed the responses were 200 in the access logs.

The bounce notifications are being processed.

Access log entry:-
"POST /civicrm/airmail/webhook?reset=1&secretcode=rv3ksU7OcCNEMP8RL2z8 HTTP/1.0" 200 0 "-" "SendGrid Event API" httpswww.example.org/civicrm/airmail/webhook?reset=1&secretcode=rv3ksU7OcCNEMP8RL2z8POST upstream_status=200 request_time=0.385 upstream_response_time=0.384 upstream_connect_time=0.001 upstream_header_time=0.384

ConfigAndLog Error :-
[error] 
$Fatal Error Details = array:3 [
  "message" => "getFieldValue failed"
  "code" => null
  "exception" => CRM_Core_Exception {#4445
    #message: "getFieldValue failed"
    #code: 0
    #file: "/var/src/drupal/site/vendor/civicrm/civicrm-core/CRM/Core/DAO.php"
    #line: 1428
    #cause: null
    -_trace: null
    -errorData: array:1 [
      "error_code" => 0
    ]
    trace: {
      /var/src/drupal/site/vendor/civicrm/civicrm-core/CRM/Core/DAO.php:1428 { …}
      /var/src/drupal/site/vendor/civicrm/civicrm-core/CRM/Dedupe/BAO/DedupeRuleGroup.php:594 { …}
      /var/src/drupal/site/vendor/civicrm/civicrm-core/CRM/Dedupe/Merger.php:2251 { …}
      /var/src/drupal/site/vendor/civicrm/civicrm-core/CRM/Contact/Page/DedupeFind.php:98 { …}
      /var/src/drupal/site/vendor/civicrm/civicrm-core/CRM/Core/Invoke.php:322 { …}
      /var/src/drupal/site/vendor/civicrm/civicrm-core/CRM/Core/Invoke.php:69 { …}
      /var/src/drupal/site/vendor/civicrm/civicrm-core/CRM/Core/Invoke.php:36 { …}
      /var/src/drupal/site/web/modules/contrib/civicrm/src/Civicrm.php:88 {
        Drupal\civicrm\Civicrm->invoke($args)
        › ob_start();
        › $content = \CRM_Core_Invoke::invoke($args);
        › $output = ob_get_clean();
        arguments: {
          $args: array:3 [ …3]
        }
      }
      /var/src/drupal/site/web/modules/contrib/civicrm/src/Controller/CivicrmController.php:83 { …}
      Drupal\civicrm\Controller\CivicrmController->main() {}
      /var/src/drupal/site/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php:123 { …}
      /var/src/drupal/site/web/core/lib/Drupal/Core/Render/Renderer.php:627 { …}
      /var/src/drupal/site/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php:124 { …}
      /var/src/drupal/site/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php:97 { …}
      /var/src/drupal/site/vendor/symfony/http-kernel/HttpKernel.php:181 { …}
      /var/src/drupal/site/vendor/symfony/http-kernel/HttpKernel.php:76 { …}
      /var/src/drupal/site/web/core/lib/Drupal/Core/StackMiddleware/Session.php:58 { …}
      /var/src/drupal/site/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php:48 { …}
      /var/src/drupal/site/web/core/lib/Drupal/Core/StackMiddleware/ContentLength.php:28 { …}
      /var/src/drupal/site/web/core/modules/big_pipe/src/StackMiddleware/ContentLength.php:32 { …}
      /var/src/drupal/site/web/core/modules/page_cache/src/StackMiddleware/PageCache.php:106 { …}
      /var/src/drupal/site/web/core/modules/page_cache/src/StackMiddleware/PageCache.php:85 { …}
      /var/src/drupal/site/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php:48 { …}
      /var/src/drupal/site/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php:51 { …}
      /var/src/drupal/site/web/core/lib/Drupal/Core/StackMiddleware/AjaxPageState.php:36 { …}
      /var/src/drupal/site/web/core/lib/Drupal/Core/StackMiddleware/StackedHttpKernel.php:51 { …}
      /var/src/drupal/site/web/core/lib/Drupal/Core/DrupalKernel.php:704 { …}
      /var/src/drupal/site/web/index.php:19 { …}
    }
  }
]

2024-10-01 14:01:10+0100  [debug] $backTrace = #0 /var/src/drupal/site/vendor/civicrm/civicrm-core/CRM/Core/Error.php(443): CRM_Core_Error::backtrace("backTrace", TRUE)
#1 /var/src/drupal/site/vendor/civicrm/civicrm-core/CRM/Core/Invoke.php(39): CRM_Core_Error::handleUnhandledException(Object(CRM_Core_Exception))
#2 /var/src/drupal/site/web/modules/contrib/civicrm/src/Civicrm.php(88): CRM_Core_Invoke::invoke((Array:3))
#3 /var/src/drupal/site/web/modules/contrib/civicrm/src/Controller/CivicrmController.php(83): Drupal\civicrm\Civicrm->invoke((Array:3))
#4 [internal function](): Drupal\civicrm\Controller\CivicrmController->main((Array:3), "")
#5 /var/src/drupal/site/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array((Array:2), (Array:2))
#6 /var/src/drupal/site/web/core/lib/Drupal/Core/Render/Renderer.php(627): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#7 /var/src/drupal/site/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(124): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure))
#8 /var/src/drupal/site/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext((Array:2), (Array:2))
#9 /var/src/drupal/site/vendor/symfony/http-kernel/HttpKernel.php(181): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#10 /var/src/drupal/site/vendor/symfony/http-kernel/HttpKernel.php(76): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#11 /var/src/drupal/site/web/core/lib/Drupal/Core/StackMiddleware/Session.php(58): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, TRUE)
#12 /var/src/drupal/site/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(48): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, TRUE)
#13 /var/src/drupal/site/web/core/lib/Drupal/Core/StackMiddleware/ContentLength.php(28): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, TRUE)
#14 /var/src/drupal/site/web/core/modules/big_pipe/src/StackMiddleware/ContentLength.php(32): Drupal\Core\StackMiddleware\ContentLength->handle(Object(Symfony\Component\HttpFoundation\Request), 1, TRUE)
#15 /var/src/drupal/site/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(106): Drupal\big_pipe\StackMiddleware\ContentLength->handle(Object(Symfony\Component\HttpFoundation\Request), 1, TRUE)
#16 /var/src/drupal/site/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(85): Drupal\page_cache\StackMiddleware\PageCache->pass(Object(Symfony\Component\HttpFoundation\Request), 1, TRUE)
#17 /var/src/drupal/site/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(48): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, TRUE)
#18 /var/src/drupal/site/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(51): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, TRUE)
#19 /var/src/drupal/site/web/core/lib/Drupal/Core/StackMiddleware/AjaxPageState.php(36): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, TRUE)
#20 /var/src/drupal/site/web/core/lib/Drupal/Core/StackMiddleware/StackedHttpKernel.php(51): Drupal\Core\StackMiddleware\AjaxPageState->handle(Object(Symfony\Component\HttpFoundation\Request), 1, TRUE)
#21 /var/src/drupal/site/web/core/lib/Drupal/Core/DrupalKernel.php(704): Drupal\Core\StackMiddleware\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, TRUE)
#22 /var/src/drupal/site/web/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#23 {main}

**Comment by dj-chalky** [comment]
I am having the same issue

**Comment by kurund** [comment]
I am not getting error mentioned in this issue however, bounces are not processed. Please check https://github.com/aghstrategies/com.aghstrategies.airmail/issues/57

**Comment by kurund** [comment]
@dwoods-encircle @dj-chalky 

Here is the patch https://github.com/aghstrategies/com.aghstrategies.airmail/pull/58 that fixes our issue.

Hope this helps!

**Comment by alifrumin** [comment]
I merged https://github.com/aghstrategies/com.aghstrategies.airmail/pull/58 did that fix this issue for you guys @dwoods-encircle?

**Comment by twomice** [comment]
Bounce processing appears to work just fine for me under master (i.e., with #58). @alifrumin what do you think about cutting a new release? (Also note, last release was almost 2 years ago, and once that crosses the 2-year mark, this extension will become unavailable for in-app installation.)

**Comment by alifrumin** [comment]
Hmm I tried to release 2.2.5 3 weeks ago but it seems like something did not go right. I will try and cut a new release and see if that helps

**Comment by twomice** [comment]
Thanks @alifrumin . Yeah, I see what you mean. I don't see anything obvious in that tag that would have caused it, but I've had similar surprises before on my own releases. 

If this one doesn't take within 24 hours, I'd reach out to bgm and ask about it; sometimes he needs to smack things around to get something unstuck.

**Comment by alifrumin** [comment]
@twomice, that’s a good tip. If this release is not published correctly on Friday I’ll check in with bgm.

Thank you!

**Comment by alifrumin** [comment]
@twomice 2.2.8 should have what you need

**Comment by twomice** [comment]
@alifrumin Glad to see that relsease went through -- yay! (BTW, any idea what was hanging up your releases?)

**Comment by alifrumin** [comment]
The emails go to Andie so it was silently failing for me.

I needed to add a documentation url 🤦‍♀️
